# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiAddNewCustomer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addNewCustomerUi(object):
    def setupUi(self, addNewCustomerUi):
        addNewCustomerUi.setObjectName("addNewCustomerUi")
        addNewCustomerUi.resize(650, 165)
        addNewCustomerUi.setMinimumSize(QtCore.QSize(650, 165))
        addNewCustomerUi.setMaximumSize(QtCore.QSize(650, 165))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addNewCustomerUi.setWindowIcon(icon)
        addNewCustomerUi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.customerOrder = QtWidgets.QLineEdit(addNewCustomerUi)
        self.customerOrder.setGeometry(QtCore.QRect(120, 20, 51, 18))
        self.customerOrder.setMinimumSize(QtCore.QSize(0, 18))
        self.customerOrder.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.customerOrder.setFont(font)
        self.customerOrder.setAlignment(QtCore.Qt.AlignCenter)
        self.customerOrder.setReadOnly(True)
        self.customerOrder.setObjectName("customerOrder")
        self.label = QtWidgets.QLabel(addNewCustomerUi)
        self.label.setGeometry(QtCore.QRect(30, 20, 90, 18))
        self.label.setMinimumSize(QtCore.QSize(90, 18))
        self.label.setMaximumSize(QtCore.QSize(90, 18))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(addNewCustomerUi)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 90, 18))
        self.label_2.setMinimumSize(QtCore.QSize(90, 18))
        self.label_2.setMaximumSize(QtCore.QSize(90, 18))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(addNewCustomerUi)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 90, 21))
        self.label_3.setMinimumSize(QtCore.QSize(90, 0))
        self.label_3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.customerCode = QtWidgets.QLineEdit(addNewCustomerUi)
        self.customerCode.setGeometry(QtCore.QRect(310, 20, 41, 18))
        self.customerCode.setMinimumSize(QtCore.QSize(0, 18))
        self.customerCode.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.customerCode.setFont(font)
        self.customerCode.setMaxLength(3)
        self.customerCode.setAlignment(QtCore.Qt.AlignCenter)
        self.customerCode.setObjectName("customerCode")
        self.customerName = QtWidgets.QLineEdit(addNewCustomerUi)
        self.customerName.setGeometry(QtCore.QRect(120, 80, 511, 18))
        self.customerName.setMinimumSize(QtCore.QSize(0, 18))
        self.customerName.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.customerName.setFont(font)
        self.customerName.setObjectName("customerName")
        self.add_record = QtWidgets.QPushButton(addNewCustomerUi)
        self.add_record.setGeometry(QtCore.QRect(550, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.add_record.setFont(font)
        self.add_record.setStyleSheet("QPushButton{\n"
"border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgba(230, 230, 230, 252);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.add_record.setObjectName("add_record")
        self.customerAddres = QtWidgets.QLineEdit(addNewCustomerUi)
        self.customerAddres.setGeometry(QtCore.QRect(120, 50, 511, 18))
        self.customerAddres.setMinimumSize(QtCore.QSize(0, 18))
        self.customerAddres.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.customerAddres.setFont(font)
        self.customerAddres.setObjectName("customerAddres")
        self.label_4 = QtWidgets.QLabel(addNewCustomerUi)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 100, 21))
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(addNewCustomerUi)
        QtCore.QMetaObject.connectSlotsByName(addNewCustomerUi)
        addNewCustomerUi.setTabOrder(self.customerOrder, self.customerCode)
        addNewCustomerUi.setTabOrder(self.customerCode, self.customerAddres)
        addNewCustomerUi.setTabOrder(self.customerAddres, self.customerName)
        addNewCustomerUi.setTabOrder(self.customerName, self.add_record)

    def retranslateUi(self, addNewCustomerUi):
        _translate = QtCore.QCoreApplication.translate
        addNewCustomerUi.setWindowTitle(_translate("addNewCustomerUi", "Yeni Müşteri Ekle"))
        self.label.setText(_translate("addNewCustomerUi", "Müşteri Sıra No:"))
        self.label_2.setText(_translate("addNewCustomerUi", "Müşteri Kodu:"))
        self.label_3.setText(_translate("addNewCustomerUi", "Müşteri Adı:"))
        self.add_record.setText(_translate("addNewCustomerUi", "KAYIT"))
        self.label_4.setText(_translate("addNewCustomerUi", "Müşteri Birlik/Adres:"))
import icons_rc
