# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiEditStandartCertificateWay.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editStandartCertificateWayUi(object):
    def setupUi(self, editStandartCertificateWayUi):
        editStandartCertificateWayUi.setObjectName("editStandartCertificateWayUi")
        editStandartCertificateWayUi.resize(590, 135)
        editStandartCertificateWayUi.setMinimumSize(QtCore.QSize(590, 135))
        editStandartCertificateWayUi.setMaximumSize(QtCore.QSize(590, 135))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/scwpath.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        editStandartCertificateWayUi.setWindowIcon(icon)
        editStandartCertificateWayUi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(editStandartCertificateWayUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 15, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_filePath = QtWidgets.QLineEdit(self.centralwidget)
        self.line_filePath.setGeometry(QtCore.QRect(30, 50, 551, 21))
        self.line_filePath.setText("")
        self.line_filePath.setReadOnly(True)
        self.line_filePath.setObjectName("line_filePath")
        self.filePathSave_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.filePathSave_Btn.setGeometry(QtCore.QRect(500, 80, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.filePathSave_Btn.setFont(font)
        self.filePathSave_Btn.setStyleSheet("QPushButton{\n"
"border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgba(230, 230, 230, 252);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.filePathSave_Btn.setObjectName("filePathSave_Btn")
        self.fileBrowse_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.fileBrowse_Btn.setGeometry(QtCore.QRect(410, 80, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.fileBrowse_Btn.setFont(font)
        self.fileBrowse_Btn.setStyleSheet("QPushButton{\n"
"border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgba(230, 230, 230, 252);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.fileBrowse_Btn.setObjectName("fileBrowse_Btn")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 40, 550, 5))
        self.line_2.setMinimumSize(QtCore.QSize(0, 5))
        self.line_2.setMaximumSize(QtCore.QSize(550, 5))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        editStandartCertificateWayUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(editStandartCertificateWayUi)
        self.statusbar.setObjectName("statusbar")
        editStandartCertificateWayUi.setStatusBar(self.statusbar)

        self.retranslateUi(editStandartCertificateWayUi)
        QtCore.QMetaObject.connectSlotsByName(editStandartCertificateWayUi)

    def retranslateUi(self, editStandartCertificateWayUi):
        _translate = QtCore.QCoreApplication.translate
        editStandartCertificateWayUi.setWindowTitle(_translate("editStandartCertificateWayUi", "Standart Sertifikalar Konumu"))
        self.label.setText(_translate("editStandartCertificateWayUi", "Standart Sertifikaların Bulunduğu Konum"))
        self.filePathSave_Btn.setText(_translate("editStandartCertificateWayUi", "KAYIT"))
        self.fileBrowse_Btn.setText(_translate("editStandartCertificateWayUi", "DOSYA SEÇ"))
import icons_rc
