# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiEditCustomer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editCustomerUi(object):
    def setupUi(self, editCustomerUi):
        editCustomerUi.setObjectName("editCustomerUi")
        editCustomerUi.resize(650, 255)
        editCustomerUi.setMinimumSize(QtCore.QSize(650, 255))
        editCustomerUi.setMaximumSize(QtCore.QSize(650, 255))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        editCustomerUi.setWindowIcon(icon)
        editCustomerUi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(editCustomerUi)
        self.label.setGeometry(QtCore.QRect(0, 10, 160, 18))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(editCustomerUi)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 611, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineSelectIsno = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSelectIsno.sizePolicy().hasHeightForWidth())
        self.lineSelectIsno.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineSelectIsno.setFont(font)
        self.lineSelectIsno.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);")
        self.lineSelectIsno.setAlignment(QtCore.Qt.AlignCenter)
        self.lineSelectIsno.setReadOnly(True)
        self.lineSelectIsno.setObjectName("lineSelectIsno")
        self.horizontalLayout_2.addWidget(self.lineSelectIsno)
        self.lineSelectBirlik = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineSelectBirlik.setFont(font)
        self.lineSelectBirlik.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);")
        self.lineSelectBirlik.setReadOnly(True)
        self.lineSelectBirlik.setObjectName("lineSelectBirlik")
        self.horizontalLayout_2.addWidget(self.lineSelectBirlik)
        self.cbSelectKod = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbSelectKod.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);")
        self.cbSelectKod.setEditable(True)
        self.cbSelectKod.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.cbSelectKod.setObjectName("cbSelectKod")
        self.horizontalLayout_2.addWidget(self.cbSelectKod)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 6)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.cbSelectHospital = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSelectHospital.sizePolicy().hasHeightForWidth())
        self.cbSelectHospital.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cbSelectHospital.setFont(font)
        self.cbSelectHospital.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);")
        self.cbSelectHospital.setEditable(True)
        self.cbSelectHospital.setCurrentText("")
        self.cbSelectHospital.setMaxVisibleItems(20)
        self.cbSelectHospital.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.cbSelectHospital.setObjectName("cbSelectHospital")
        self.verticalLayout_2.addWidget(self.cbSelectHospital)
        self.line_2 = QtWidgets.QFrame(editCustomerUi)
        self.line_2.setGeometry(QtCore.QRect(20, 100, 611, 5))
        self.line_2.setMinimumSize(QtCore.QSize(0, 5))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 5))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(editCustomerUi)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 90, 18))
        self.label_2.setMinimumSize(QtCore.QSize(90, 18))
        self.label_2.setMaximumSize(QtCore.QSize(90, 18))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.editCustomerOrder = QtWidgets.QLineEdit(editCustomerUi)
        self.editCustomerOrder.setGeometry(QtCore.QRect(100, 120, 51, 18))
        self.editCustomerOrder.setMinimumSize(QtCore.QSize(0, 18))
        self.editCustomerOrder.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.editCustomerOrder.setFont(font)
        self.editCustomerOrder.setStyleSheet("border: 1px solid; ")
        self.editCustomerOrder.setAlignment(QtCore.Qt.AlignCenter)
        self.editCustomerOrder.setReadOnly(True)
        self.editCustomerOrder.setObjectName("editCustomerOrder")
        self.label_3 = QtWidgets.QLabel(editCustomerUi)
        self.label_3.setGeometry(QtCore.QRect(180, 120, 90, 18))
        self.label_3.setMinimumSize(QtCore.QSize(90, 18))
        self.label_3.setMaximumSize(QtCore.QSize(90, 18))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.editCustomerCode = QtWidgets.QLineEdit(editCustomerUi)
        self.editCustomerCode.setGeometry(QtCore.QRect(260, 120, 41, 18))
        self.editCustomerCode.setMinimumSize(QtCore.QSize(0, 18))
        self.editCustomerCode.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.editCustomerCode.setFont(font)
        self.editCustomerCode.setStyleSheet("border: 1px solid; ")
        self.editCustomerCode.setMaxLength(3)
        self.editCustomerCode.setAlignment(QtCore.Qt.AlignCenter)
        self.editCustomerCode.setObjectName("editCustomerCode")
        self.editCustomerAddres = QtWidgets.QLineEdit(editCustomerUi)
        self.editCustomerAddres.setGeometry(QtCore.QRect(100, 150, 531, 18))
        self.editCustomerAddres.setMinimumSize(QtCore.QSize(0, 18))
        self.editCustomerAddres.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.editCustomerAddres.setFont(font)
        self.editCustomerAddres.setStyleSheet("border: 1px solid; ")
        self.editCustomerAddres.setObjectName("editCustomerAddres")
        self.label_4 = QtWidgets.QLabel(editCustomerUi)
        self.label_4.setGeometry(QtCore.QRect(0, 150, 100, 21))
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.editCustomerName = QtWidgets.QLineEdit(editCustomerUi)
        self.editCustomerName.setGeometry(QtCore.QRect(100, 180, 531, 18))
        self.editCustomerName.setMinimumSize(QtCore.QSize(0, 18))
        self.editCustomerName.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.editCustomerName.setFont(font)
        self.editCustomerName.setStyleSheet("border: 1px solid; ")
        self.editCustomerName.setObjectName("editCustomerName")
        self.label_5 = QtWidgets.QLabel(editCustomerUi)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 90, 21))
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.edit_record = QtWidgets.QPushButton(editCustomerUi)
        self.edit_record.setGeometry(QtCore.QRect(550, 210, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.edit_record.setFont(font)
        self.edit_record.setStyleSheet("QPushButton{\n"
"border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgba(230, 230, 230, 252);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.edit_record.setObjectName("edit_record")

        self.retranslateUi(editCustomerUi)
        self.cbSelectHospital.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(editCustomerUi)

    def retranslateUi(self, editCustomerUi):
        _translate = QtCore.QCoreApplication.translate
        editCustomerUi.setWindowTitle(_translate("editCustomerUi", "Müşteri Düzenle"))
        self.label.setText(_translate("editCustomerUi", "Düzenlecek Müşteri Seçimi"))
        self.label_2.setText(_translate("editCustomerUi", "Müşteri Sıra No:"))
        self.label_3.setText(_translate("editCustomerUi", "Müşteri Kodu:"))
        self.label_4.setText(_translate("editCustomerUi", "Müşteri Birlik/Adres:"))
        self.label_5.setText(_translate("editCustomerUi", "Müşteri Adı:"))
        self.edit_record.setText(_translate("editCustomerUi", "DEĞİŞTİR"))
import icons_rc
